# Generated by Django 4.2.7 on 2023-12-10 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Elo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Fila",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "status",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_elo", models.CharField(max_length=50, null=True)),
                ("current_elo_image", models.CharField(max_length=100, null=True)),
                ("target_elo", models.CharField(max_length=50, null=True)),
                ("target_elo_image", models.CharField(max_length=100, null=True)),
                ("description", models.TextField(max_length=500, null=True)),
                ("riot_login", models.CharField(max_length=50, null=True)),
                ("riot_password", models.CharField(max_length=50, null=True)),
                ("refer_code", models.CharField(max_length=50, null=True)),
                ("payment_method", models.CharField(default="Pix", max_length=50, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("riot_id", models.CharField(max_length=50, null=True)),
                ("riot_tag", models.CharField(default="#BR1", max_length=50, null=True)),
                ("time", models.IntegerField(null=True)),
                ("purchase_date", models.DateField(auto_now_add=True, null=True)),
                (
                    "queue",
                    models.ForeignKey(
                        default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.fila"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicos_type",
                        to="core.modalidade",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="servicos_status",
                        to="core.status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
